#checking secrets

name: test_secret

on:
  workflow_dispatch:
  
  workflow_call:
    secrets:
      GITHUB_TOKEN:
        description: 'GH token'
        required: false

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@v3

      - name: One-line script
        run: | 
          gh secret list
