#checking secrets

name: test_secret

on:
  workflow_dispatch:

env:
    GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check gh secrets
        run: | 
          export GITHUB_TOKEN=""
          echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token
          gh api \
            -H "Accept: application/vnd.github+json" \
            /orgs/rocknrolldevs/actions/secrets/test
