#checking secrets

name: test_secret

on:
  workflow_dispatch:

env:
  GH_TOKEN: ${{ secrets.MY_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@v3
      - name: Check gh secrets
        run: | 
          gh secret set new_secret
