name: test_secret

on:
  workflow_dispatch:

env:
  GH_TOKEN: ${{ secrets.MY_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@v3
      - name: Raise VM
        run: | 
          
      
      - name: Raise vm
        run: | 
          gh secret set secret-name < secret.txt
